--- #YAML:1.0
name:                Mail-Box
version:             2.090
abstract:            E-mail handling
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Format:                  0
    Date::Parse:                   0
    Digest::HMAC_MD5:              0
    Encode:                        2.26
    Errno:                         0
    File::Remove:                  0.20
    File::Spec:                    0.7
    IO::Scalar:                    0
    Mail::Address:                 0
    MIME::Base64:                  0
    MIME::Types:                   1.004
    Object::Realize::Later:        0.14
    Scalar::Util:                  1.13
    Sys::Hostname:                 0
    TAP::Harness:                  3.00
    Test::More:                    0.47
    Test::Pod:                     1.00
    Time::Zone:                    0
    URI:                           1.23
    User::Identity:                0.90
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
