# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Box
version:      2.059
version_from: lib/Mail/Box.pm
installdirs:  site
requires:
    Date::Parse:                   0
    Digest::HMAC_MD5:              0
    Errno:                         0
    File::Remove:                  0.2
    File::Spec:                    0.7
    IO::Scalar:                    0
    Mail::Address:                 0
    MIME::Base64:                  0
    MIME::Types:                   1.004
    Object::Realize::Later:        0.14
    Scalar::Util:                  1.13
    Sys::Hostname:                 0
    Test::Harness:                 1.38
    Test::More:                    0.47
    Time::Zone:                    0
    URI:                           1.23
    User::Identity:                0.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
