---
abstract: 'E-mail handling'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Box
no_index:
  directory:
    - t
    - inc
requires:
  Date::Format: 0
  Date::Parse: 0
  Devel::GlobalDestruction: 0.09
  Digest::HMAC_MD5: 0
  Encode: 2.26
  Errno: 0
  File::Remove: 0.20
  File::Spec: 0.7
  IO::Scalar: 0
  MIME::Base64: 0
  MIME::Types: 1.004
  Mail::Address: 0
  Object::Realize::Later: 0.19
  Scalar::Util: 1.13
  Sys::Hostname: 0
  TAP::Harness: 3.00
  Test::More: 0.47
  Test::Pod: 1.00
  Time::Zone: 0
  URI: 1.23
  User::Identity: 0.94
version: 2.114
