--- #YAML:1.0
name:                Mail-Box
version:             2.074
abstract:            E-mail handling
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Date::Parse:                   0
    Digest::HMAC_MD5:              0
    Errno:                         0
    File::Remove:                  0.2
    File::Spec:                    0.7
    IO::Scalar:                    0
    Mail::Address:                 0
    MIME::Base64:                  0
    MIME::Types:                   1.004
    Object::Realize::Later:        0.14
    Scalar::Util:                  1.13
    Sys::Hostname:                 0
    Test::Harness:                 2.62
    Test::More:                    0.47
    Test::Pod:                     1
    Time::Zone:                    0
    URI:                           1.23
    User::Identity:                0.9
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Overmeer
