
=head1 NAME

Mail::Box-Index - list of all extended documentation




=head1 DESCRIPTION

All methods defined by MailBox are documented, but you still need to
get a grip on the large picture: the relations between the modules
and the methods.  These larger explanations are included in the
DETAILS of the manual pages, and listed here below.  Of course, each
page has a DESCRIPTION section as well, which tells some bare necessities
about the module.

Only the HTML version of this manual page will list the sections.

=begin :html

<ol>
<li><strong><a name="general">General</a> sources of information</strong>
  <ul>
  <li>MailBox distribution overview (L<Mail::Box-Overview|Mail::Box-Overview>)
      <ul>
      <li>L<Mail::Box-Overview/Introduction>
      <li>L<Mail::Box-Overview/The class relations>
      <li>L<Mail::Box-Overview/The Manager>
      <li>L<Mail::Box-Overview/The Messages>
      <li>L<Mail::Box-Overview/The Folder types>
      <li>L<Mail::Box-Overview/Various Other Classes>
      </ul>
  <li>MailBox simple recepies (L<Mail::Box-Cookbook|Mail::Box-Cookbook>)
      <ul>
      <li>L<Mail::Box-Cookbook/The Manager>
      <li>L<Mail::Box-Cookbook/Multi part messages>
      <li>L<Mail::Box-Cookbook/Filter>
      <li>L<Mail::Box-Cookbook/Create a reply>
      <li>L<Mail::Box-Cookbook/Build a message>
      </ul>
  </ul>

<li><strong><a name="messages">Messages</a></strong> (L<Mail::Message|Mail::Message>)
      See separate entries on header, body, fields
      and construction in this index below.
  <ul>
  <li>L<Mail::Message/Structure of a Message>
      <ul>
      <li>L<Mail::Message/The header> 
      <li>L<Mail::Message/The body> 
      </ul>
  <li>Coercing messages
  <li>L<Mail::Message/Message object implementation>
  <li>L<Mail::Message/Message class implementation>
  </ul>

<li><strong><a name="headers">Message headers</a></strong> (L<Mail::Message::Head|Mail::Message::Head>)
  <ul>
  <li>L<Mail::Message::Head/Ordered header fields>
  <li>L<Mail::Message::Field/Resent groups> (L<Mail::Message::Head::ResentGroup|Mail::Message::Head::ResentGroup>)
  <li>L<Mail::Message::Head/Head class implementation>
  </ul>

<li><strong><a name="fields">Message header fields</a></strong> (L<Mail::Message::Field|Mail::Message::Field>)
  <ul>
  <li>L<Mail::Message::Field/Field syntax>
      <ul>
      <li>L<Mail::Message::Field/Folding fields>
      <li>L<Mail::Message::Field/Structured fields>
      <li>L<Mail::Message::Field/Comments in fields>
      </ul>
  <li>L<Mail::Message::Field/Getting a field>
      <ul>
      <li>L<Mail::Message::Field/Using get() field>
      <li>L<Mail::Message::Field/Using study() field>
      <li>L<Mail::Message::Field/Resent groups> L<Mail::Message::Head::ResentGroup|Mail::Message::Head::ResentGroup>
      </ul>
  <li>L<Mail::Message::Field/The field's data>
      <ul>
      <li>L<Mail::Message::Field/Access to the field>
      <li>L<Mail::Message::Field/Using simplified field access>
      </ul>
  <li>L<Mail::Message::Field/Field class implementation>
  </ul>

<li><strong><a name="bodies">Message bodies</a></strong> (L<Mail::Message::Body|Mail::Message::Body>)
  <ul>
  <li>L<Mail::Message::Body/Access to the body>
  <li>Body meta information
      <ul>
      <li>Content types (L<MIME::Types>)
      <li>Content transfer encoding (L<Mail::Message::TransferEnc|Mail::Message::TransferEnc>)
      </ul>
  <li>Multipart bodies (L<Mail::Message::Body::Multipart|Mail::Message::Body::Multipart>)
  <li>Nested (encapsulated) messages (L<Mail::Message::Body::Nested|Mail::Message::Body::Nested>)
  <li>L<Mail::Message::Body/Body class implementation>
      <ul>
      <li>L<Mail::Message::Body/Data collector bodies>
      <li>L<Mail::Message::Body/Complex bodies>
      </ul>
  </ul>

<li><strong><a name="labels">Message labels</a></strong>
  <ul>
  <li>L<Mail::Message/Labels> (L<Mail::Message|Mail::Message>)
      <ul>
      <li>L<Mail::Message/Predefined labels> (L<Mail::Message|Mail::Message>)
  <li>Storing labels folder dependent
      <li>L<Mail::Box::Maildir::Message/Flags in filename> (L<Mail::Box::Maildir::Message|Mail::Box::Maildir::Message>)
      <li>L<Mail::Box::Mbox::Message/Status and X-Status fields> (L<Mail::Box::Mbox::Message|Mail::Box::Mbox::Message>)
      <li>L<Mail::Box::MH::Message/The .mh_sequences file> (L<Mail::Box::MH::Labels|Mail::Box::MH::Labels>)
      <li>L<Mail::Box::IMAP4::Message/IMAP protocol flags> (L<Mail::Box::IMAP4::Message|Mail::Box::IMAP4::Message>)
      </ul>
  </ul>

<li><strong><a name="process">Message processing</a></strong>
  <ul>
  <li>Reading a message (L<Mail::Message::Construct::Read|Mail::Message::Construct::Read>)
  <li>Building a message (L<Mail::Message::Construct::Build|Mail::Message::Construct::Build>)
  <li>Reply to a message (L<Mail::Message::Construct::Reply|Mail::Message::Construct::Reply>)
  <li>Forward a message (L<Mail::Message::Construct::Forward|Mail::Message::Construct::Forward>)
  <li>Bounce a message (L<Mail::Message::Construct::Bounce|Mail::Message::Construct::Bounce>)
  <li>L<Mail::Message::Construct::Rebuild/Rebuilding a message> (L<Mail::Message::Construct::Rebuild|Mail::Message::Construct::Rebuild>)
      <ul>
      <li>L<Mail::Message::Construct::Rebuild/General rules>
      <li>L<Mail::Message::Construct::Rebuild/Conversion rules>
      <li>L<Mail::Message::Construct::Rebuild/Adding your own rules>
      </ul>
  <li>Convert messages
      <ul>
      <li>To and from Mail::Internet objects (L<Mail::Message::Convert::MailInternet|Mail::Message::Convert::MailInternet>)
      <li>To and from MIME::Entity objects(L<Mail::Message::Convert::MimeEntity|Mail::Message::Convert::MimeEntity>)
      <li>Into HTML (L<Mail::Message::Convert::Html|Mail::Message::Convert::Html>)
      </ul>
  <li>Convert body contents
      <ul>
      <li>From HTML to PostScript (L<Mail::Message::Convert::HtmlFormatPS|Mail::Message::Convert::HtmlFormatPS>)
      <li>From HTML into plain text (L<Mail::Message::Convert::HtmlFormatText|Mail::Message::Convert::HtmlFormatText>)
      <li>Beautify text (L<Mail::Message::Convert::TextAutoformat|Mail::Message::Convert::TextAutoformat>)
      </ul>
  </ul>

<li><strong><a name="folders">Folders</a></strong> (L<Mail::Box|Mail::Box>)
      See separate section for type specifics below.
  <ul>
  <li>Folder types (L<Mail::Box|Mail::Box>)
      <ul>
      <li>L<Mail::Box/Different kinds of folders>
      <li>L<Mail::Box/Supported folder types>
      <li>L<Mail::Box/Folder class implementation>
      </ul>
  <li>The folder manager (L<Mail::Box::Manager|Mail::Box::Manager>)
  <li>L<Mail::Box::Tie::ARRAY/Folder tied as array> (L<Mail::Box::Tie::ARRAY|Mail::Box::Tie::ARRAY>)
      <ul>
      <li>L<Mail::Box::Tie::ARRAY/Limitations>
      </ul>
  <li>Folder tied as hash (L<Mail::Box::Tie::HASH|Mail::Box::Tie::HASH>)
  <li>Folder locking (L<Mail::Box::Locker|Mail::Box::Locker>)
  <li>Searching folders (L<Mail::Box::Search|Mail::Box::Search>)
      <ul>
      <li>scan header and body (L<Mail::Box::Search::Grep|Mail::Box::Search::Grep>)
      <li>check for spam (L<Mail::Box::Search::SpamAssassin|Mail::Box::Search::SpamAssassin>) 
      </ul>
  </ul>

<li><strong><a name="ftypes">Folder types</a></strong>
  <ul>
  <li>DBX folders (L<Mail::Box::Dbx|Mail::Box::Dbx>, read only)
      <ul>
      <li>L<Mail::Box::Dbx/How DBX folders work>
      <li>L<Mail::Box::Dbx/This implementation>
      <li>L<Mail::Box::Dbx/Converting DBX folders to MBOX>
      </ul>
  <li>IMAP4 folders (L<Mail::Box::IMAP4|Mail::Box::IMAP4>)
      <ul>
      <li>L<Mail::Box::IMAP4/How IMAP4 folders work>
      </ul>
  <li>MAILDIR folders (L<Mail::Box::Maildir|Mail::Box::Maildir>)
      <ul>
      <li>L<Mail::Box::Maildir/How MAILDIR folders work>
      </ul>
  <li>MBOX folders (L<Mail::Box::Mbox|Mail::Box::Mbox>)
      <ul>
      <li>L<Mail::Box::Mbox/How MBOX folders work>
      <li>L<Mail::Box::Mbox/Simulation of sub-folders>
      </ul>
  <li>MH folders (L<Mail::Box::MH|Mail::Box::MH>)
      <ul>
      <li>L<Mail::Box::MH/How MH folders work>
      <li>L<Mail::Box::MH/This implementation>
      <li>L<Mail::Box::MH/An index-file>
      </ul>
  <li>POP3 folders (L<Mail::Box::POP3|Mail::Box::POP3>)
      <ul>
      <li>L<Mail::Box::POP3/How POP3 folders work>
      <li>L<Mail::Box::POP3/This implementation>
      </ul>
  </ul>

<li><strong><a name="threads">Discussion threads</a></strong>
  <ul>
  <li>The thread manager (L<Mail::Box::Thread::Manager|Mail::Box::Thread::Manager>)
      <ul>
      <li>L<Mail::Box::Thread::Manager/Maintaining threads>
      <li>L<Mail::Box::Thread::Manager/Delayed thread detection>
      </ul>
  <li>The thread node (L<Mail::Box::Thread::Node|Mail::Box::Thread::Node>)
  </ul>

<li><strong><a name="send">Transmitting messages</a></strong> (L<Mail::Transport|Mail::Transport>)
  <ul>
  <li>Sending (L<Mail::Transport::Send|Mail::Transport::Send>)
      <ul>
      <li>Via Exim (L<Mail::Transport::Exim|Mail::Transport::Exim>)
      <li>Via Mailx (L<Mail::Transport::Mailx|Mail::Transport::Mailx>)
      <li>Via Qmail (L<Mail::Transport::Qmail|Mail::Transport::Qmail>)
      <li>Via Sendmail or Postfix (L<Mail::Transport::Sendmail|Mail::Transport::Sendmail>)
      <li>Via raw SMTP (L<Mail::Transport::SMTP|Mail::Transport::SMTP>)
      </ul>
  <li>Receiving (L<Mail::Transport::Receive|Mail::Transport::Receive>)
      <ul>
      <li>Via POP3 (L<Mail::Transport::POP3|Mail::Transport::POP3>)
      </ul>
  <li>Bi-directional
      <ul>
      <li>Via IMAP4 (L<Mail::Transport::IMAP4|Mail::Transport::IMAP4>)
      </ul>
  </ul>

<li><strong><a name="perform">Performance</a></strong>
  <ul>
  <li>Quality over performance
  <li>Lazy extraction
  <li>Weak references
  <li>Destructing messages (L<Mail::Box::Message::Destructed|Mail::Box::Message::Destructed>)
  <li>Using the right class
      <ul>
      <li>Picking the optimal body class
      <li>Removing superfluous header fields (L<Mail::Message::Head::Partial|Mail::Message::Head::Partial>)
      </ul>
  <li>Helper modules
      <ul>
      <li>Install Mail::Box::Parser::C
      <li>L<MIME::Types|http://perl.overmeer.net/mimetypes/html/>
      <li>L<Object::Realize::Later>
      <li>L<User::Identity|http://perl.overmeer.net/userid/html/>
      </ul>
  </ul>
</ol>

=end :html










=head1 REFERENCES

See the Mail::Box website at L<http://perl.overmeer.net/mailbox/> for more details.

=head1 COPYRIGHTS

Module version 2.043.
Written by Mark Overmeer (mark@overmeer.net).  See the ChangeLog for
other contributors.

Copyright (c) 2001-2003 by the author(s). All rights reserved.
This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.


